Revert "postrm-init: Tweak to avoid triggering a lintian warning"
This reverts commit 2059ab8e431cd7ba8392f79c70950e44ce04dc64.

diff --git a/autoscripts/postrm-init b/autoscripts/postrm-init
--- a/autoscripts/postrm-init
+++ b/autoscripts/postrm-init
@@ -1,13 +1,12 @@
-if [ "$1" = "remove" ] || [ "$1" = "purge" ] ; then
-	_action=remove
-	if [ "$1" = "remove" ] ; then
-		# Attempt to disable but ignore failures as it is not
-		# required (and the script must be a able to handle
-		# being called while the package is removed, but not
-		# yet purged)
-		_action=disable
-	fi
-	update-rc.d #SCRIPT# ${_action} >/dev/null
+if [ "$1" = "remove" ] ; then
+	# Attempt to disable but ignore failures as it is not
+	# required (and the script must be a able to handle
+	# being called while the package is removed, but not
+	# yet purged)
+	update-rc.d #SCRIPT# disable >/dev/null || true
+fi
+if [ "$1" = "purge" ] ; then
+	update-rc.d #SCRIPT# remove >/dev/null
 fi
 
 
