autoscripts/postinst-*: Handle all current abort-* cases
Signed-off-by: Niels Thykier <niels@thykier.net>

diff --git a/autoscripts/postinst-systemd-restart b/autoscripts/postinst-systemd-restart
--- a/autoscripts/postinst-systemd-restart
+++ b/autoscripts/postinst-systemd-restart
@@ -1,6 +1,6 @@
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 		if [ -d /run/systemd/system ]; then
-		systemctl --system daemon-reload >/dev/null || true
+			systemctl --system daemon-reload >/dev/null || true
 		if [ -n "$2" ]; then
 			_dh_action=restart
 		else
