dh_installsystemduser: fix daemon-reload of user instances
'systemctl --global daemon-reload' does not actually exist, and never did.
Fix it by using '--no-dbus' for the postrm case, where it's fine to use
async signals as there's no need to block, and and the normal version
for the postinst case where it needs to block in order to allow the unit
start to work immediately afterwards.

Fixes: ea8e48c1bf82 ("dh_installsystemduser: add support for starting/stopping user units")

diff --git a/autoscripts/postinst-systemd-user-restart b/autoscripts/postinst-systemd-user-restart
--- a/autoscripts/postinst-systemd-user-restart
+++ b/autoscripts/postinst-systemd-user-restart
@@ -1,6 +1,11 @@
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -z "${DPKG_ROOT:-}" ] && [ -d /run/systemd/system ]; then
-		systemctl --global daemon-reload >/dev/null || true
+		# Here we reload synchronously, as we really need to block in
+		# order to ensure the following restart also works. Furthermore,
+		# if there is no D-Bus user session, the restart won't work either,
+		# so there's no point if falling back to signals - so either both
+		# of these operations work, or both fail.
+		deb-systemd-invoke --user daemon-reload >/dev/null || true
 		deb-systemd-invoke --user restart #UNITFILES# >/dev/null || true
 	fi
 fi
